.TH "BufferedFileInputStreamReader" 3 "Version 1.0.0" "CPgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BufferedFileInputStreamReader
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBInputStreamReader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBufferedFileInputStreamReader\fP (std::FILE *file, const std::string &name)"
.br
.ti -1c
.RI "void \fBsetTestCase\fP (int)"
.br
.ti -1c
.RI "std::vector< int > \fBgetReadChars\fP ()"
.br
.ti -1c
.RI "int \fBcurChar\fP ()"
.br
.ti -1c
.RI "int \fBnextChar\fP ()"
.br
.ti -1c
.RI "void \fBskipChar\fP ()"
.br
.ti -1c
.RI "void \fBunreadChar\fP (int c)"
.br
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.ti -1c
.RI "int \fBgetLine\fP ()"
.br
.ti -1c
.RI "bool \fBeof\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void BufferedFileInputStreamReader::close ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.SS "int BufferedFileInputStreamReader::curChar ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.SS "bool BufferedFileInputStreamReader::eof ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.SS "int BufferedFileInputStreamReader::getLine ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.SS "std::string BufferedFileInputStreamReader::getName ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.SS "std::vector< int > BufferedFileInputStreamReader::getReadChars ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.SS "int BufferedFileInputStreamReader::nextChar ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.SS "void BufferedFileInputStreamReader::setTestCase (int)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.SS "void BufferedFileInputStreamReader::skipChar ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.
.SS "void BufferedFileInputStreamReader::unreadChar (int c)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBInputStreamReader\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPgen from the source code\&.
