.TH "Checker" 3 "Version 1.0.0" "CPgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Checker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "std::string \fBtestset\fP () const"
.br
.ti -1c
.RI "std::string \fBgroup\fP () const"
.br
.ti -1c
.RI "void \fBsetTestset\fP (const char *const testset)"
.br
.ti -1c
.RI "void \fBsetGroup\fP (const char *const group)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CPgen from the source code\&.
