.TH "GenException" 3 "Version 1.0.0" "CPgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenException \- The exception throwed when errors occured\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <generator\&.h>\fP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenException\fP (std::string msg)"
.br
.ti -1c
.RI "\fBGenException\fP (const char *msg)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const  throw ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_msg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The exception throwed when errors occured\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CPgen from the source code\&.
