.TH "Geometry< PointType >" 3 "Version 1.0.0" "CPgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Geometry< PointType >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fB_Tp\fP = \fBPoint\fP<PointType>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBrandomize_points\fP (int size, \fB_Tp\fP leftbottom, \fB_Tp\fP rightup)"
.br
.ti -1c
.RI "void \fBmake_raw_convex_shell\fP (int size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "std::set< \fB_Tp\fP > \fBpoints\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CPgen from the source code\&.
