.TH "InputStreamReader" 3 "Version 1.0.0" "CPgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputStreamReader
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBufferedFileInputStreamReader\fP, \fBFileInputStreamReader\fP, and \fBStringInputStreamReader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetTestCase\fP (int testCase)=0"
.br
.ti -1c
.RI "virtual std::vector< int > \fBgetReadChars\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBcurChar\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBnextChar\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBskipChar\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBunreadChar\fP (int c)=0"
.br
.ti -1c
.RI "virtual std::string \fBgetName\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBeof\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBclose\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBgetLine\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CPgen from the source code\&.
