.TH "pattern" 3 "Version 1.0.0" "CPgen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pattern
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpattern\fP (std::string s)"
.br
.ti -1c
.RI "std::string \fBnext\fP (\fBrandom_t\fP &rnd) const"
.br
.ti -1c
.RI "bool \fBmatches\fP (const std::string &s) const"
.br
.ti -1c
.RI "std::string \fBsrc\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CPgen from the source code\&.
